apiVersion: v1
kind: ConfigMap
metadata:
  name: yas-configuration-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  application.yaml: |
    server:
      shutdown: graceful
      port: 80
    management:
      server:
        port: 8090
      endpoints:
        web:
          exposure:
            include: prometheus,health
      endpoint:
        health:
          probes:
            enabled: true
    spring:
      datasource:
        username: ${POSTGRESQL_USERNAME}
        password: ${POSTGRESQL_PASSWORD}
      kafka:
        bootstrap-servers: kafka-cluster-kafka-brokers.kafka:9092
    yas:
      services:
        cart: http://cart/cart
        customer: http://customer/customer
        inventory: http://inventory/inventory
        location: http://location/location
        media: http://media/media
        order: http://order/order
        payment: http://payment/payment
        payment-paypal: http://payment-paypal/payment-paypal
        product: http://product/product
        promotion: http://promotion/promotion
        rating: http://rating/rating
        search: http://search/search
        tax: http://tax/tax
        sampledata: http://sampledata/sampledata
        recommendation: http://recommendation/recommendation
  logback.xml: |
    <configuration>
      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>%d %-5level [%thread] %logger{36} - %msg%n</pattern>
        </encoder>
      </appender>
      <root level="INFO">
        <appender-ref ref="STDOUT" />
      </root>
    </configuration>
---
apiVersion: v1
kind: Secret
metadata:
  name: yas-postgresql-credentials-secret
  annotations:
    reloader.stakater.com/match: "true"
type: Opaque
stringData:
  POSTGRESQL_USERNAME: lab-postgres-user
  POSTGRESQL_PASSWORD: lab-postgres-password
